### ISSUE TITLE
User lookup by usernames Error response issue

### ISSUE THREAD

**Issue by roblack** [daneden/Twift#8]
I am not 100% sure if my setup is wrong, but if one searches for multiple users, ie, the request has an array of parameters....if one of them produces an error, the whole response is nil 🤷‍♂️

Here is the example of such a response on twitter developer portal:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/21968377/159134893-22738e6b-2091-409b-ba52-e07ba609c837.png">

@daneden
You can see in the screenshot what is the setup. Basically, find a character that produces an error ("e" is one of them), and send several other strings along with it in a single response.

**Comment by roblack** [comment]
![image](https://user-images.githubusercontent.com/21968377/159368886-3012913b-d819-4fce-8fcb-2fb9945719b6.png)

So it seems it is not fully migrated, but possibly not planned at all? 🤷‍♂️

**Comment by daneden** [comment]
@roblack thanks for reporting this issue! First it's worth pointing out that “user lookup” is different from “user search”.

- User *lookup* assumes that you already know the complete username of the user you’re trying to fetch info for (i.e. a lookup for `ja` would only return the user `@ja`)
- User *search* is a function to find users by username with an incomplete string (i.e. a search for `ja` might return `@jack`)

User search is not (yet) in the V2 API, but lookup is. Nevertheless, the error you reported is valid and needs fixing; when a subset of user names passed to the lookup endpoint returns an error, Twift should return an array of error objects instead of returning an error for the whole request.

**Comment by daneden** [comment]
I found the cause of this bug!

In the `decodeOrThrow` method that is responsible for decoding all requests to the Twitter API, I had written the method in a way that always throws errors when they’re encountered, even if a successful payload is returned along with errors.

In https://github.com/daneden/Twift/commit/1f47b9374a55ac47a27d9841a309a2b3fb98d051, I changed it so that Twift only throws errors when found if a successful response can’t be decoded.
